name: Hello Actions

on:
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  
  workflow_dispatch:
    inputs:
      greeting_name:
        description: 'Name to include in the greeting'
        required: false
        default: 'World'

  schedule:
    - cron: '35 12 * * *'


jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, ${{ github.event.inputs.greeting_name || 'World' }}! This run was triggered by a ${{ github.event_name }} event."

      - name: Show the operating system
        run: cat /etc/os-release

      - name: List files (before checkout)
        run: |
          pwd
          ls -la
      
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: python -m pytest
      
      - name: Show tool versions
        run: |
          python --version
          pytest --version
          ruff --version

      - name: list files (after checkout)
        run: ls -la
